### ISSUE TITLE
Supporting code coverage

### ISSUE THREAD

**Issue by pcaixeta** [valotas/karma-parcel#23]
I'm starting this more like a question because I haven't found anything about it around the internet: Is it possible to add code coverage with karma-parcel?

This is an amazing tool, thank you for it, it was very simple to get my tests up and running with Typescript and web components, but I'm having a hard time adding the code coverage report. =(

**Comment by valotas** [comment]
Hi @pcaixeta thanks a lot for the interest. Unfortunately I did not spend time on it.

**Comment by pcaixeta** [comment]
Oh =(
Is it on your roadmap?

**Comment by valotas** [comment]
Well, instrumenting code created by parcel is definitely not in scope of this project. Maybe you can have a look at how to configure parcel with babel-plugin-istanbul
