### ISSUE TITLE
"Cannot resolve dependency"

### ISSUE THREAD

**Issue by gambolputty** [valotas/karma-parcel#7]
Hey!

when running karma I get the following error message at the beginning:

> ×  C:\Users\Gregor\AppData\Local\Temp\karma-parcel-entry-1549208002648.js:2:7: Cannot resolve dependency './G:/Git/projectname/src/main.js' at 'C:\Users\Gregor\AppData\Local\Temp\G:\Git\projectname\src\main.js'
  1 | import "./G:/Git/projectname/src/logger.js";
> 2 | import "./G:/Git/projectname/src/main.js";
    |       ^
  3 | import "./G:/Git/projectname/src/settings.js";
  4 | import "./G:/Git/projectname/src/util.js";

Somehow it falsely resolves the paths. In my karma config file, I have no `basePath` defined. When I set it to './' (karma.config.js resides inside the root folder of my project) it has no effect.

*Windows 10*
*Node v10.15.1*
*Parcel 1.11.0*

I configured my karma.conf.js like described in the readme.
Is this related `karma-parcel`?

**Comment by valotas** [comment]
Hi, thanks for the report

I believe it is a bug. I am about to push a new version which does not make use of the temp folder as I had quite some problems myself. Should be out the following days. Stay tuned.

**Comment by gambolputty** [comment]
Thanks a lot!

**Comment by valotas** [comment]
Would you like to try with `v0.3`?

**Comment by valotas** [comment]
@gambolputty do you still have problems with the dependencies resolution? Can I close this?

**Comment by gambolputty** [comment]
Hey @valotas, sorry for not responding earlier. I haven't had the time to check out the new release(s) and sadly won't be able to in the near future. Please close this issue, I'm not able to report back :/
