### ISSUE TITLE
Cannot find module parcel-bundler

### ISSUE THREAD

**Issue by ashubham** [valotas/karma-parcel#8]
Seems, we have used the `parcel-bundler` alias for the parcel package in the code. But in the docs we are using `parcel`. It will be great to change the code to use `parcel` package instead as it seems to be the more standard.

**Comment by valotas** [comment]
Hi @ashubham 

I am afraid I do not understand what exactly you mean by code and doc. Would you like to point me to the file you are referring to?

**Comment by ashubham** [comment]
In the docs you mention:
`npm i parcel` for installation

In the code you use `parcel-bundler`
https://github.com/valotas/karma-parcel/blob/master/src/plugin.ts#L8

These both are the same packages with different names, `parcel` being the more used now. Maybe change the code to use `parcel` too.
